import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/NavBar";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={`${inter.className} w-screen flex h-screen flex-col `}>
        <Toaster position="top-center" reverseOrder={false} />
        <nav className="w-full flex mb-20">
          <NavBar />
        </nav>
        {children}
      </body>
    </html>
  );
}
